SOURCE = greenBookListDriver.cpp  ../common/src/List.cpp
HEADERS = ../common/include/List.h

ListTest: 
	g++ -o greenBookListDriver -g $(SOURCE) $(HEADERS)

clean:
	-rm -f *.o
	-rm -f greenBookListDriver
